### ISSUE TITLE
Support for GHC plugin

### ISSUE THREAD

**Issue by plredmond** [ucsd-progsys/liquid-types.vim#2]
Hello! Does liquid-types.vim have support for the upcoming liquid-haskell-as-GHC plugin architecture? Is support planned?

**Comment by plredmond** [comment]
I'm referring to this. :) https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Plugin/Tutorial.hs

**Comment by ranjitjhala** [comment]
Hi @plredmond, yes one nice thing about the Pluto is it basically makes LH
errors the same as GHC compilation errors so existing editor support (for
GHC) should work pretty much out of the box!

**Comment by plredmond** [comment]
OK! I don't use anything like that in vim currently, so I'll look into it. :) Thank you!

**Comment by ranjitjhala** [comment]
See the section on “ale” here

https://wiki.haskell.org/Vim

I think with some luck that should work! I will try it myself on the “demo”
package here

https://github.com/ucsd-progsys/lh-plugin-demo
